version: '2'

services:
  server:
    build:
      dockerfile: server/Dockerfile
    ports:
      - 8181:8181
  client:
    build: 
      dockerfile: client/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./client/:/usr/share/nginx/html