version: '2'

services:
  # Config do server
  server:
    build:
      context: server/
      dockerfile: Dockerfile.dev
    ports:
      - 8181:8181
    volumes:
      - ./server/server.js:/usr/src/app/server.js
  # Config do client
  client:
    build: 
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html