version: '2'

services:
#   server:
#     build:
#       context: .
#       dockerfile: server/Dockerfile
#     ports:
#       - 8181:8181
  client:
    build: 
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./client/:/usr/share/nginx/html